=== EzBl4ck/TPS/Nov12p1/src/es1/trekking.dtd
<!ELEMENT trekking-all (trekking*)>
<!ELEMENT destinazione (#PCDATA)>
<!ELEMENT data_partenza (#PCDATA)>
<!ELEMENT giorni_durata (#PCDATA)>
<!ELEMENT costo (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT cognome (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT guida (nome, cognome, email)>
<!ELEMENT min_partecipanti (#PCDATA)>
<!ELEMENT partenza (#PCDATA)>
<!ELEMENT destinazione_tappa (#PCDATA)>
<!ELEMENT distanza_km (#PCDATA)>
<!ELEMENT dislivello (#PCDATA)>
<!ELEMENT tappa (partenza, destinazione_tappa, distanza_km, dislivello)>
<!ELEMENT tappe (tappa+)>
<!ELEMENT trekking (destinazione, data_partenza, giorni_durata, costo, guida, min_partecipanti, tappe)>

=== EzBl4ck/TPS/Nov12p1/src/es1/trekking.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trekking-all SYSTEM "trekking.dtd">
<trekking-all>
	<trekking>
		<destinazione>Milano</destinazione>
		<data_partenza>10/10/23</data_partenza>
		<giorni_durata>5</giorni_durata>
		<costo>50</costo>
		<guida>
			<nome>Paolo</nome>
			<cognome>Rossi</cognome>
			<email>paolo.rossi@aaaa.it</email>
		</guida>
		<min_partecipanti>10</min_partecipanti>
		<tappe>
			<tappa>
				<partenza>Roma</partenza>
				<destinazione_tappa>Milano</destinazione_tappa>
				<distanza_km>500</distanza_km>
				<dislivello>0</dislivello>
			</tappa>
		</tappe>
	</trekking>
</trekking-all>
