=== EzBl4ck/TPS/XML/3_11/biblioteca.dtd
<!ELEMENT biblioteca (libri)>
<!ELEMENT libri (libro*)>
<!ELEMENT libro (titolo, genere, autori, codice)>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT genere (#PCDATA)>
<!ELEMENT autori (autore+)>
<!ELEMENT codice (#PCDATA)>
<!ELEMENT autore (nome, cognome, eta)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT cognome (#PCDATA)>
<!ELEMENT eta (#PCDATA)>

=== EzBl4ck/TPS/XML/3_11/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
	<libri>
		<libro>
			<titolo>Titolo 1</titolo>
			<genere>Genere 1</genere>
			<autori>
				<autore>
					<nome>Nome 1</nome>
					<cognome>Cognome 1</cognome>
					<eta>10</eta>
				</autore>
				<autore>
					<nome>Nome 2</nome>
					<cognome>Cognome 2</cognome>
					<eta>20</eta>
				</autore>
			</autori>
			<codice>1</codice>
		</libro>
		<libro>
			<titolo>Titolo 2</titolo>
			<genere>Genere 2</genere>
			<autori>
				<autore>
					<nome>Nome 3</nome>
					<cognome>Cognome 3</cognome>
					<eta>30</eta>
				</autore>
			</autori>
			<codice>2</codice>
		</libro>
	</libri>
</biblioteca>
