=== EzBl4ck/TPS/XML/3_11/squadra.dtd
<!ELEMENT squadra (nome, serie, presidente, allenatore, giocatori+, massaggiatore*)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT serie (#PCDATA)>
<!ELEMENT presidente (#PCDATA)>
<!ELEMENT allenatore (#PCDATA)>
<!ELEMENT giocatori (giocatore+)>
<!ELEMENT giocatore (nome_giocatore, ruoli, titolare)>
<!ELEMENT nome_giocatore (#PCDATA)>
<!ELEMENT ruoli (ruolo+)>
<!ELEMENT ruolo (#PCDATA)>
<!ELEMENT titolare (#PCDATA)>
<!ELEMENT massaggiatore (#PCDATA)>

=== EzBl4ck/TPS/XML/3_11/squadra.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE squadra SYSTEM "squadra.dtd">
<squadra>
    <nome>Juminter</nome>
    <serie>C1</serie>
    <presidente>Mario Rossi</presidente>
    <allenatore>Giuseppe Bianchi</allenatore>
    <giocatori>
        <giocatore>
            <nome_giocatore>Leonardo Da Vinci</nome_giocatore>
            <ruoli>
                <ruolo>Terzino</ruolo>
            </ruoli>
            <titolare>true</titolare>
        </giocatore>
        <giocatore>
            <nome_giocatore>Cristoforo Colombo</nome_giocatore>
            <ruoli>
                <ruolo>Attaccante</ruolo>
                <ruolo>Mezzala</ruolo>
            </ruoli>
            <titolare>false</titolare>
        </giocatore>
        <giocatore>
            <nome_giocatore>Giulio Cesare</nome_giocatore>
            <ruoli>
                <ruolo>Difensore</ruolo>
            </ruoli>
            <titolare>true</titolare>
        </giocatore>
    </giocatori>
</squadra>
