=== EzBl4ck/TPS/Nov12p1/src/es3/consegna_auto.dtd
<!ELEMENT consegna_auto (mese+)>
<!ELEMENT mese (modello+)>
<!ATTLIST mese nome NMTOKEN #REQUIRED>
<!ELEMENT modello (nome,num)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT num (#PCDATA)>

=== EzBl4ck/TPS/Nov12p1/src/es3/consegna_auto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE consegna_auto SYSTEM "consegna_auto.dtd">
<consegna_auto>
	<mese nome="gennaio">
		<modello>
			<nome>ModelloA</nome>
			<num>50</num>
		</modello>
		<modello>
			<nome>ModelloB</nome>
			<num>500</num>
		</modello>
	</mese>
	<mese nome="febbraio">
		<modello>
			<nome>ModelloX</nome>
			<num>5</num>
		</modello>
		<modello>
			<nome>ModelloB</nome>
			<num>10</num>
		</modello>
		<modello>
			<nome>ModelloE</nome>
			<num>200</num>
		</modello>
	</mese>
	<mese nome="marzo">
		<modello>
			<nome>ModelloA</nome>
			<num>100</num>
		</modello>
	</mese>
</consegna_auto>
